import type { Config } from 'tailwindcss';

const config: Config = {
  darkMode: ['class'],
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        // SQLCraft Design System - "The Architectural Lab"
        'on-tertiary-fixed-variant': '#004e59',
        'on-secondary-fixed': '#00201d',
        'outline-variant': '#454652',
        'tertiary': '#44d8f1',
        'primary': '#bac3ff',
        'surface-dim': '#131313',
        'secondary-fixed': '#84f5e8',
        'on-tertiary': '#00363e',
        'on-background': '#e5e2e1',
        'on-tertiary-container': '#55e4fd',
        'surface-container-high': '#2a2a2a',
        'on-primary-fixed-variant': '#2f3f92',
        'on-primary-fixed': '#00105b',
        'on-surface': '#e5e2e1',
        'surface-container-highest': '#353534',
        'on-surface-variant': '#c5c5d4',
        'surface-tint': '#bac3ff',
        'inverse-on-surface': '#313030',
        'on-primary-container': '#c9cfff',
        'surface-container-lowest': '#0e0e0e',
        'inverse-primary': '#4858ab',
        'secondary': '#66d9cc',
        'primary-container': '#4453a7',
        'on-tertiary-fixed': '#001f25',
        'surface-container-low': '#1c1b1b',
        'tertiary-fixed-dim': '#44d8f1',
        'tertiary-fixed': '#a1efff',
        'primary-fixed': '#dee0ff',
        'on-secondary-container': '#00302b',
        'inverse-surface': '#e5e2e1',
        'tertiary-container': '#006471',
        'outline': '#8f909e',
        'error-container': '#93000a',
        'surface-bright': '#393939',
        'surface': '#131313',
        'secondary-fixed-dim': '#66d9cc',
        'on-error': '#690005',
        'on-secondary-fixed-variant': '#005049',
        'on-error-container': '#ffdad6',
        'surface-container': '#201f1f',
        'background': '#131313',
        'secondary-container': '#1ea296',
        'primary-fixed-dim': '#bac3ff',
        'on-secondary': '#003732',
        'surface-variant': '#353534',
        'error': '#ffb4ab',
        'on-primary': '#15267b',
      },
      fontFamily: {
        headline: ['Space Grotesk', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        label: ['Inter', 'sans-serif'],
        mono: ['JetBrains Mono', 'monospace'],
        sans: ['Inter', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        sm: '0.125rem',
        md: '0.375rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      backdropBlur: {
        glass: '12px',
      },
    },
  },
  plugins: [],
};

export default config;
