import type { Config } from 'tailwindcss';

const config: Config = {
  darkMode: ['class'],
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        // Content-first neutral — dark without feeling flat (#0a); clearer layers
        'on-tertiary-fixed-variant': '#5c5c5c',
        'on-secondary-fixed': '#1a1a1a',
        'outline-variant': '#3d3d3d',
        'tertiary': '#7a7a7a',
        'primary': '#e8e8e8',
        'surface-dim': '#121212',
        'secondary-fixed': '#d4d4d4',
        'on-tertiary': '#fafafa',
        'on-background': '#ececec',
        'on-tertiary-container': '#e8e8e8',
        'surface-container-high': '#2a2a2a',
        'on-primary-fixed-variant': '#5c5c5c',
        'on-primary-fixed': '#121212',
        'on-surface': '#ececec',
        'surface-container-highest': '#333333',
        'on-surface-variant': '#a8b0bc',
        'surface-tint': '#e8e8e8',
        'inverse-on-surface': '#1a1a1a',
        'on-primary-container': '#e8e8e8',
        'surface-container-lowest': '#121212',
        'inverse-primary': '#1a1a1a',
        'secondary': '#a3a3a3',
        'primary-container': '#343434',
        'on-tertiary-fixed': '#121212',
        'surface-container-low': '#1e1e1e',
        'tertiary-fixed-dim': '#737373',
        'tertiary-fixed': '#d4d4d4',
        'primary-fixed': '#e8e8e8',
        'on-secondary-container': '#d4d4d4',
        'inverse-surface': '#ececec',
        'tertiary-container': '#484848',
        'outline': '#4d4d4d',
        'error-container': '#322828',
        'surface-bright': '#383838',
        'surface': '#161616',
        'secondary-fixed-dim': '#a3a3a3',
        'on-error': '#1a1010',
        'on-secondary-fixed-variant': '#5c5c5c',
        'on-error-container': '#e8d8d8',
        'surface-container': '#222222',
        'background': '#161616',
        'secondary-container': '#2e2e2e',
        'primary-fixed-dim': '#d4d4d4',
        'on-secondary': '#121212',
        'surface-variant': '#2e2e2e',
        'error': '#c4a8a8',
        'on-primary': '#121212',
      },
      fontFamily: {
        headline: ['var(--font-space-grotesk)', 'sans-serif'],
        body: ['var(--font-inter)', 'sans-serif'],
        label: ['var(--font-inter)', 'sans-serif'],
        mono: ['var(--font-jetbrains-mono)', 'monospace'],
        sans: ['var(--font-inter)', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        sm: '0.125rem',
        md: '0.375rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      backdropBlur: {
        glass: '12px',
      },
    },
  },
  plugins: [],
};

export default config;
