import type { SchemaSqlDialect } from '@sqlcraft/types';

export type SqlDialectConfidence = 'high' | 'medium' | 'low';

/**
 * Heuristic dialect detection from raw dump text.
 * Uses a bounded window for very large files.
 *
 * Two-layer approach:
 *  1. Tool headers — unambiguous signatures from pg_dump / mysqldump / sqlcmd etc.
 *  2. Structural syntax — dialect-specific SQL constructs that appear in the dump body,
 *     independent of how the dump was generated.
 */
export function inferSqlDialectFromDump(rawUtf8: string): {
  inferredDialect: SchemaSqlDialect;
  dialectConfidence: SqlDialectConfidence;
} {
  const windowSize = 12 * 1024 * 1024;
  const w = rawUtf8.length <= windowSize ? rawUtf8 : rawUtf8.slice(0, windowSize);

  let pg = 0;
  let mysql = 0;
  let mariadb = 0;
  let sqlite = 0;
  let mssql = 0;

  // ── Layer 1: Tool-generated headers (high confidence) ──────────────────────

  // PostgreSQL — pg_dump standard headers
  if (/--\s*PostgreSQL database dump/i.test(w)) pg += 20;
  if (/--\s*Dumped (by|from) pg_dump\b/i.test(w)) pg += 20;
  if (/--\s*Dumped from database/i.test(w)) pg += 8;

  // MySQL / MariaDB — mysqldump headers
  if (/--\s*MySQL dump\b/i.test(w)) mysql += 20;
  if (/mysqldump\b/i.test(w)) mysql += 15;
  if (/--\s*MariaDB dump\b/i.test(w)) mariadb += 20;
  if (/MariaDB server version/i.test(w)) mariadb += 15;

  // SQL Server — sqlcmd / SSMS / BCP headers
  if (/--\s*Microsoft SQL Server/i.test(w)) mssql += 20;
  if (/--\s*Generated by.*SQL Server/i.test(w)) mssql += 20;
  if (/--.*\bSQL\s+SERVER\b/i.test(w)) mssql += 12;

  // SQLite
  if (/--\s*SQLite\b/i.test(w)) sqlite += 20;

  // ── Layer 2: Structural syntax (dialect-specific constructs) ───────────────
  // These appear in the dump body regardless of how the dump was generated.

  // PostgreSQL-exclusive syntax
  if (/\bCOPY\s+\S+\s+\([^)]+\)\s+FROM\s+stdin\b/i.test(w)) pg += 20; // pg_dump bulk copy
  if (/\\connect\b/i.test(w)) pg += 10;                                 // psql meta-command
  if (/\$\$[\s\S]{0,500}\$\$/m.test(w)) pg += 8;                       // dollar-quoting
  if (/\bSERIAL\b|\bBIGSERIAL\b/i.test(w)) pg += 6;                    // pg serial types
  if (/\bCREATE\s+SEQUENCE\b/i.test(w)) pg += 5;
  if (/::[\w\s[\]]+/i.test(w)) pg += 5;                               // pg cast syntax
  if (/\bRETURNING\b/i.test(w)) pg += 4;
  if (/\bON\s+CONFLICT\b/i.test(w)) pg += 4;

  // MySQL/MariaDB-exclusive syntax
  if (/ENGINE\s*=\s*(InnoDB|MyISAM|MEMORY|ARCHIVE)\b/i.test(w)) mysql += 15;
  if (/AUTO_INCREMENT\s*=/i.test(w)) mysql += 10;
  if (/\/\*!\d{5}/.test(w)) mysql += 12;                               // mysql version comments /*!50003
  if (/LOCK\s+TABLES\s+`/i.test(w)) mysql += 10;
  if (/`[^`]+`\s+`[^`]+`/i.test(w)) mysql += 6;                       // backtick identifiers
  if (/CHARACTER\s+SET\s+\w+/i.test(w)) mysql += 5;
  if (/\bDEFAULT\s+CHARSET\s*=/i.test(w)) mysql += 8;
  if (/\bINSERT\s+INTO\s+`/i.test(w)) mysql += 5;                      // backtick table in INSERT

  // MariaDB extras
  if (/\bMARIADB\b/i.test(w)) mariadb += 8;

  // SQL Server-exclusive syntax
  if (/^\s*GO\s*$/im.test(w)) mssql += 15;                             // T-SQL batch separator
  if (/\bSET\s+ANSI_NULLS\s+ON\b/i.test(w)) mssql += 8;
  if (/\bSET\s+QUOTED_IDENTIFIER\s+ON\b/i.test(w)) mssql += 8;
  if (/\bSET\s+NOCOUNT\s+ON\b/i.test(w)) mssql += 6;
  if (/\[[\w\s]+\]\s*\[[\w\s]+\]/i.test(w)) mssql += 10;              // [dbo].[tableName] bracket notation
  if (/\bIDENTITY\s*\(\s*\d+\s*,\s*\d+\s*\)/i.test(w)) mssql += 10;  // IDENTITY(1,1)
  if (/\bNVARCHAR\s*\(/i.test(w)) mssql += 6;
  if (/\bNVARCHAR\s*\(\s*MAX\s*\)/i.test(w)) mssql += 8;
  if (/\bDATETIME2\b/i.test(w)) mssql += 8;
  if (/\bUNIQUEIDENTIFIER\b/i.test(w)) mssql += 8;
  if (/\bGETDATE\s*\(\)/i.test(w)) mssql += 6;
  if (/\bNEWID\s*\(\)/i.test(w)) mssql += 6;
  if (/\bWITH\s*\(\s*NOLOCK\s*\)/i.test(w)) mssql += 6;
  if (/\bSYSOBJECTS\b/i.test(w)) mssql += 8;
  if (/\bOBJECT_ID\s*\(/i.test(w)) mssql += 6;
  if (/\bDROP\s+TABLE\s+IF\s+EXISTS\s+\[/i.test(w)) mssql += 8;       // DROP TABLE IF EXISTS [dbo].[...]
  if (/\bCREATE\s+TABLE\s+\[/i.test(w)) mssql += 8;                   // CREATE TABLE [dbo].[...]
  if (/\bDROP\s+DATABASE\s+IF\s+EXISTS\b/i.test(w)) mssql += 5;       // T-SQL DDL

  // SQLite-exclusive syntax
  if (/^\s*PRAGMA\b/im.test(w)) sqlite += 15;
  if (/\bINTEGER\s+PRIMARY\s+KEY\s+AUTOINCREMENT\b/i.test(w)) sqlite += 12;

  // ── Scoring ────────────────────────────────────────────────────────────────
  const ranked = [
    { dialect: 'postgresql' as const, score: pg },
    { dialect: 'mysql' as const, score: mysql + mariadb * 0.5 },
    { dialect: 'mariadb' as const, score: mariadb },
    { dialect: 'sqlite' as const, score: sqlite },
    { dialect: 'sqlserver' as const, score: mssql },
  ].sort((a, b) => b.score - a.score);

  const best = ranked[0]!;
  const second = ranked[1]!;

  if (best.score === 0) {
    return { inferredDialect: 'postgresql', dialectConfidence: 'low' };
  }
  if (best.score >= 15 && best.score - second.score >= 8) {
    return { inferredDialect: best.dialect, dialectConfidence: 'high' };
  }
  if (best.score >= 8 && best.score - second.score >= 4) {
    return { inferredDialect: best.dialect, dialectConfidence: 'medium' };
  }
  if (best.score > second.score) {
    return { inferredDialect: best.dialect, dialectConfidence: 'low' };
  }

  return { inferredDialect: 'postgresql', dialectConfidence: 'low' };
}
