FROM node:20-alpine

WORKDIR /app

RUN apk add --no-cache docker-cli
RUN npm install -g pnpm

COPY package.json pnpm-workspace.yaml pnpm-lock.yaml .npmrc ./
COPY packages/types/package.json ./packages/types/
COPY packages/config/package.json ./packages/config/
COPY services/worker/package.json ./services/worker/

RUN pnpm install --frozen-lockfile

COPY packages ./packages
COPY services/worker ./services/worker

WORKDIR /app/services/worker

CMD ["pnpm", "dev"]
